name: 构建并发布 PAC 文件

on:
  # 手动触发工作流
  workflow_dispatch:
  # 定时任务，每周一 UTC 时间 0:00 运行（相当于北京时间 8:00）
  schedule:
    - cron: '0 0 * * 1'
  # 当推送到 main 分支时触发
  push:
    branches:
      - main

# 设置必要的权限
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: 运行 PAC 生成脚本
        run: |
          python3 generate_pac.py
        
      - name: 获取当前日期
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      
      - name: 创建 Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.date.outputs.DATE }}
          name: PAC 更新 ${{ steps.date.outputs.DATE }}
          body: |
            PAC 文件自动更新 - ${{ steps.date.outputs.DATE }}
            
            本次更新包含了最新的中国域名列表和代理域名列表。
          files: |
            output/proxy.pac
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}